### ISSUE TITLE
use `pre-commit` for git hooks

### ISSUE THREAD

**Issue by SauravMaheshkar** [robota-suite/robota-core#20]
As the project moves forwards and adapts to use more static code analysis tools such as `ruff`(#18) and `mypy`(#17) it might be suitable to achieve parity between CI and dev by running same/similar workflows. 

[pre-commit](https://pre-commit.com/) is one such tool that would make that process much easier and enforce that the developers follow coding conventions even before it reaches CI.

A very simple config file could look like:
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
```
